<?php

namespace Database\Seeders;

use App\Models\Assignment;
use App\Models\Batch;
use App\Models\Beneficiary;
use App\Models\Code;
use App\Models\Credential;
use App\Models\Implementation;
use App\Models\SystemsLog;
use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\UserSetting;
use App\Services\JaccardSimilarity;
use Carbon\Carbon;
use Illuminate\Support\Facades\Hash;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    protected $implementationAmount = 100;
    protected $coordinatorsAmount = 10;
    protected $assignmentAmountMin = 2;
    protected $assignmentAmountMax = 6;
    protected $batchAmountMin = 2;
    protected $batchAmountMax = 6;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $startDate = Carbon::createFromDate(2023, 9, 29);

        // $admin = User::factory()->create([
        //     'first_name' => 'TU-Admin',
        //     'middle_name' => '-',
        //     'last_name' => '-',
        //     'extension_name' => '-',
        //     'email' => 'tuefficient@gmail.com',
        //     'password' => Hash::make('password'),
        //     'contact_num' => fake()->phoneNumber(),
        //     'regional_office' => null,
        //     'field_office' => null,
        //     'user_type' => 'admin',
        // ]);

        // SystemsLog::factory()->create([
        //     'users_id' => $admin['id'],
        //     'log_timestamp' => $startDate,
        //     'description' => $admin['first_name'] . ' has been created as admin.'
        // ]);

        // $rFocalUser = User::factory()->create([
        //     'field_office' => null,
        //     'user_type' => 'r_focal',
        // ]);

        // SystemsLog::factory()->create([
        //     'users_id' => $rFocalUser['id'],
        //     'log_timestamp' => $startDate,
        //     'description' => $this->getFullName($rFocalUser) . ' has been created as regional office focal.'
        // ]);

        $focalUser = User::factory()->create([
            'user_type' => 'focal',
        ]);

        SystemsLog::factory()->create([
            'users_id' => $focalUser->id,
            'log_timestamp' => $startDate,
            'description' => $this->getFullName($focalUser) . ' has been created as field office focal.'
        ]);

        $coordinatorUsers = User::factory($this->coordinatorsAmount)->create();

        foreach ($coordinatorUsers as $key => $user) {
            SystemsLog::factory()->create([
                'users_id' => $user->id,
                'log_timestamp' => $startDate,
                'description' => $this->getFullName($user) . ' has been created as ' . $focalUser->regional_office . ' coordinator.'
            ]);
        }

        # Uncomment and use this only when adding additional settings
        # also remove all existing settings if you're adding new settings
        # so that it won't overwrite the settings in production
        // $focalUser = User::where('user_type', 'focal')->get();
        // $coordinatorUsers = User::where('user_type', 'coordinator')->get();

        $settingsFocal = [
            'minimum_wage' => config('settings.minimum_wage'),
            'duplication_threshold' => config('settings.duplication_threshold'),
            'project_number_prefix' => config('settings.project_number_prefix'),
            'batch_number_prefix' => config('settings.batch_number_prefix'),
        ];

        $settingsCoordinator = [
            'minimum_wage' => config('settings.minimum_wage'),
            'duplication_threshold' => config('settings.duplication_threshold'),
        ];

        foreach ($settingsFocal as $key => $setting) {
            $initSetting = UserSetting::factory()->create([
                'users_id' => $focalUser->id,
                'key' => $key,
                'value' => $setting,
            ]);

            SystemsLog::factory()->create([
                'users_id' => null,
                'log_timestamp' => $startDate,
                'description' => 'A setting ' . $initSetting['key'] . ' has been initialized with ' . $initSetting['value'] . ' for ' . $this->getFullName(person: $focalUser) . '.'
            ]);
        }

        foreach ($coordinatorUsers as $user) {
            foreach ($settingsCoordinator as $key => $setting) {
                $initSetting = UserSetting::factory()->create([
                    'users_id' => $user->id,
                    'key' => $key,
                    'value' => $setting,
                ]);

                SystemsLog::factory()->create([
                    'users_id' => null,
                    'log_timestamp' => $startDate,
                    'description' => 'A setting ' . $initSetting['key'] . ' has been initialized with ' . $initSetting['value'] . ' for ' . $this->getFullName(person: $user) . '.'
                ]);
            }
        }

        $project_title = ucwords('implementation number');
        $implementations = Implementation::factory($this->implementationAmount)->create(
            [
                'users_id' => $focalUser->id,
            ]
        );

        foreach ($implementations as $key => $implementation) {
            Implementation::withoutTimestamps(function () use ($implementation, $project_title, $key) {
                $implementation->project_title = $project_title . ' ' . $key + 1;
                $implementation->save();
            });

            SystemsLog::factory()->create([
                'users_id' => $focalUser->id,
                'log_timestamp' => $implementation->updated_at,
                'description' => 'Created an implementation project ' . $implementation['project_num'] . '.',
            ]);
        }

        $batches = $implementations->flatMap(function ($implementation) {
            $currentDate = $implementation->created_at;
            $allottedSlots = $this->generateRandomArray($implementation->total_slots);

            return collect($allottedSlots)->map(function ($slots) use ($implementation, $currentDate) {
                return Batch::factory()->create([
                    'implementations_id' => $implementation->id,
                    'barangay_name' => $this->getBarangayName($implementation->id),
                    'slots_allocated' => $slots,
                    'created_at' => $currentDate,
                    'updated_at' => $currentDate,
                ]);
            });
        });

        foreach ($batches as $batch) {
            SystemsLog::factory()->create([
                'users_id' => $focalUser->id,
                'log_timestamp' => $batch->updated_at,
                'description' => 'Created a batch assignment ' . $batch->batch_num . ' in project ' . Implementation::find($batch->implementations_id)->value('project_num') . '.',
            ]);

            $amount = mt_rand($this->assignmentAmountMin, $this->assignmentAmountMax);
            $coordinators = $coordinatorUsers->random($amount);
            $currentDate = $batch->created_at;

            $coordinators->each(function ($user) use ($batch, $currentDate, $focalUser) {
                Assignment::factory()->create([
                    'batches_id' => $batch->id,
                    'users_id' => $user->id,
                    'created_at' => $currentDate,
                    'updated_at' => $currentDate,
                ]);

                SystemsLog::factory()->create([
                    'users_id' => $focalUser->id,
                    'log_timestamp' => $currentDate,
                    'description' => 'Assigned ' . $this->getFullName($user) . ' in batch ' . $batch->batch_num . '.',
                ]);
            });
        }

        $focalUserId = $focalUser->id; // example focal user id
        $batches = Batch::join('implementations', 'implementations.id', '=', 'batches.implementations_id')
            ->select(['batches.*', 'implementations.district'])
            ->get();

        foreach ($batches as $batch) {
            Batch::withoutTimestamps(function () use ($batch) {
                $batch->submission_status = 'submitted';
                $batch->save();
            });

            SystemsLog::factory()->create([
                'users_id' => $focalUserId,
                'log_timestamp' => $batch->updated_at,
                'description' => 'Marked batch ' . $batch->batch_num . ' as submitted.',
            ]);

            $code = Code::factory()->create(['batches_id' => $batch->id]);

            SystemsLog::factory()->create([
                'users_id' => $focalUserId,
                'log_timestamp' => $batch->updated_at,
                'description' => 'Created an access code for Batch ' . $code->access_code . '.',
            ]);

            $beneficiaries = Beneficiary::factory($batch->slots_allocated)->create([
                'batches_id' => $batch->id,
                'barangay_name' => $batch->barangay_name,
                'district' => $batch->district,
                'created_at' => $batch->created_at,
                'updated_at' => $batch->updated_at,
            ]);

            $specialCases = 0;
            foreach ($beneficiaries as $beneficiary) {

                # check its Jaccard Similarity index
                $beneficiariesInDatabase = $this->prefetchNames($beneficiary, $this->getFullName($beneficiary), $beneficiary->middle_name);
                $joiningFrequency = 1;

                # this is where it checks the similarities
                foreach ($beneficiariesInDatabase as $key => $existing) {

                    # gets the full name of the beneficiary
                    $existingPerson = $this->getFullName2($existing, $beneficiary->middle_name);
                    $currentPerson = $this->getFullName2($beneficiary, $beneficiary->middle_name);

                    # gets the co-efficient/jaccard index of the 2 names (without birthdate by default)
                    $coEfficient = JaccardSimilarity::calculateSimilarity($existingPerson, $currentPerson);

                    # check if it's a perfect duplicate
                    if (intval($coEfficient * 100) === 100) {

                        # if the current beneficiary is the same as the existing beneficiary...
                        if ($existingPerson === $currentPerson) {

                            # if the exact same person joined more than 2 times...
                            if ($joiningFrequency > 1) {
                                Beneficiary::withoutTimestamps(function () use ($beneficiary) {
                                    $first_name = $this->getFirstName($beneficiary->sex);
                                    $middle_name = $this->getMiddleName();
                                    $last_name = $this->getLastName();
                                    $extension_name = $this->getSuffix();
                                    $s_first_name = $this->checkSpouse($beneficiary->civil_status, $beneficiary->sex, 'first');
                                    $s_middle_name = $this->checkSpouse($beneficiary->civil_status, $beneficiary->sex, 'middle');
                                    $s_last_name = $this->checkSpouse($beneficiary->civil_status, $beneficiary->sex, 'last', $last_name);
                                    $s_extension_name = $this->checkSpouse($beneficiary->civil_status, $beneficiary->sex, 'ext');

                                    $beneficiary->first_name = $first_name;
                                    $beneficiary->middle_name = $middle_name;
                                    $beneficiary->last_name = $last_name;
                                    $beneficiary->extension_name = $extension_name;
                                    $beneficiary->spouse_first_name = $s_first_name;
                                    $beneficiary->spouse_middle_name = $s_middle_name;
                                    $beneficiary->spouse_last_name = $s_last_name;
                                    $beneficiary->spouse_extension_name = $s_extension_name;
                                    $beneficiary->save();
                                });
                            }

                            # otherwise...
                            else {
                                # increment its joining frequency
                                $joiningFrequency++;

                                Beneficiary::withoutTimestamps(function () use ($beneficiary) {
                                    $beneficiary->beneficiary_type = 'special case';
                                    $beneficiary->save();
                                });
                                # then add the reason for joining
                                Credential::factory()->create([
                                    'beneficiaries_id' => $beneficiary->id,
                                    'image_description' => 'This beneficiary is a calamity victim.',
                                    'for_duplicates' => 'yes',
                                    'created_at' => $batch->created_at,
                                    'updated_at' => $batch->updated_at,
                                ]);
                                $specialCases++;
                            }
                        }

                        # otherwise...
                        else {

                            # tell the reason if they are not the same person
                            Credential::factory()->create([
                                'beneficiaries_id' => $beneficiary->id,
                                'image_description' => 'Not the same person.',
                                'for_duplicates' => 'yes',
                                'created_at' => $batch->created_at,
                                'updated_at' => $batch->updated_at,
                            ]);
                        }
                    }
                }

                Credential::factory()->create([
                    'beneficiaries_id' => $beneficiary->id,
                    'created_at' => $batch->created_at,
                    'updated_at' => $batch->updated_at,
                ]);
            }

            SystemsLog::factory()->create([
                'users_id' => $focalUser->id,
                'log_timestamp' => $batch->updated_at,
                'description' => 'Added (' . $batch->slots_allocated . ') beneficiaries with (' . $specialCases . ') special cases in batch ' . $batch->batch_num . '.',
            ]);

        }
    }

    protected function refreshBeneficiary($beneficiary)
    {
        Beneficiary::withoutTimestamps(function () use ($beneficiary) {
            $first_name = $this->getFirstName($beneficiary->sex);
            $middle_name = $this->getMiddleName();
            $last_name = $this->getLastName();
            $extension_name = $this->getSuffix();
            $s_first_name = $this->checkSpouse($beneficiary->civil_status, $beneficiary->sex, 'first');
            $s_middle_name = $this->checkSpouse($beneficiary->civil_status, $beneficiary->sex, 'middle');
            $s_last_name = $this->checkSpouse($beneficiary->civil_status, $beneficiary->sex, 'last', $last_name);
            $s_extension_name = $this->checkSpouse($beneficiary->civil_status, $beneficiary->sex, 'ext');

            $beneficiary->first_name = $first_name;
            $beneficiary->middle_name = $middle_name;
            $beneficiary->last_name = $last_name;
            $beneficiary->extension_name = $extension_name;
            $beneficiary->spouse_first_name = $s_first_name;
            $beneficiary->spouse_middle_name = $s_middle_name;
            $beneficiary->spouse_last_name = $s_last_name;
            $beneficiary->spouse_extension_name = $s_extension_name;
            $beneficiary->save();
        });
    }

    protected function prefetchNames($beneficiary, string $filteredInputString, string|null $middle_name)
    {
        # only take beneficiaries from the start of the year until today
        $startDate = now()->startOfYear();
        $endDate = now();

        # separate each word from all the name fields
        # and get the first letter of each word
        $namesToLetters = array_map(fn($word) => $word[0], explode(' ', $filteredInputString));

        $beneficiariesFromDatabase = Beneficiary::join('batches', 'beneficiaries.batches_id', '=', 'batches.id')
            ->join('implementations', 'batches.implementations_id', '=', 'implementations.id')
            ->whereBetween('implementations.created_at', [$startDate, $endDate])
            ->whereNotIn('beneficiaries.id', [$beneficiary->id])
            ->where(function ($query) use ($namesToLetters) {
                foreach ($namesToLetters as $letter) {
                    $query->orWhere('beneficiaries.first_name', 'LIKE', $letter . '%');
                }
            })
            ->where(function ($q) use ($namesToLetters, $middle_name) {
                $q->when($middle_name, function ($q) use ($namesToLetters) {
                    foreach ($namesToLetters as $letter) {
                        $q->orWhere('beneficiaries.middle_name', 'LIKE', $letter . '%');
                    }
                });
                foreach ($namesToLetters as $letter) {
                    $q->orWhere('beneficiaries.last_name', 'LIKE', $letter . '%');
                }
            })
            ->select([
                'beneficiaries.*'
            ])
            ->get();


        return $beneficiariesFromDatabase;
    }

    function getFullName2($person, $middle_name)
    {
        $name = $person->first_name;

        if ($middle_name) {
            $name .= ' ' . $person->middle_name;
        }

        $name .= ' ' . $person->last_name;

        if ($person->extension_name) {
            $name .= ' ' . $person->extension_name;
        }
        return $name;
    }

    function getFullName($person)
    {
        $name = $person->first_name;

        if ($person->middle_name) {
            $name .= ' ' . $person->middle_name;
        }

        $name .= ' ' . $person->last_name;

        if ($person->extension_name) {
            $name .= ' ' . $person->extension_name;
        }
        return $name;
    }

    function generateRandomArray($totalValue, $minThresholdPercentage = 15)
    {
        // Determine the number of values (2 to 6)
        $numValues = mt_rand($this->batchAmountMin, $this->batchAmountMax);

        // Minimum threshold for each value
        $minThreshold = $totalValue * ($minThresholdPercentage / 100);

        // Initialize the array
        $values = [];

        // Generate random values ensuring each is above the minimum threshold
        for ($i = 0; $i < $numValues - 1; $i++) {
            $maxPossible = $totalValue - (($numValues - $i - 1) * $minThreshold);
            $values[$i] = mt_rand($minThreshold, $maxPossible);
            $totalValue -= $values[$i];
        }

        // Adjust the values to make sure the sum equals the initial total value
        $values[] = $totalValue;

        return $values;
    }

    function getBarangayName($implementationId): string
    {
        $district = Implementation::find($implementationId)->district;
        $barangays = $this->getBarangaysByDistrict($district);

        do {
            $barangay = fake()->randomElement($barangays);
        } while (Batch::where('implementations_id', $implementationId)->where('barangay_name', $barangay)->exists());

        return $barangay;
    }

    function getBarangaysByDistrict(string $district): array
    {
        $barangayList = [
            '1st District' => [
                '1-A',
                '2-A',
                '3-A',
                '4-A',
                '5-A',
                '6-A',
                '7-A',
                '8-A',
                '9-A',
                '10-A',
                '11-B',
                '12-B',
                '13-B',
                '14-B',
                '15-B',
                '16-B',
                '17-B',
                '18-B',
                '19-B',
                '20-B',
                '21-C',
                '22-C',
                '23-C',
                '24-C',
                '25-C',
                '26-C',
                '27-C',
                '28-C',
                '29-C',
                '30-C',
                '31-D',
                '32-D',
                '33-D',
                '34-D',
                '35-D',
                '36-D',
                '37-D',
                '38-D',
                '39-D',
                '40-D',
                'Bago Aplaya',
                'Bago Gallera',
                'Baliok',
                'Bucana',
                'Catalunan Grande',
                'Catalunan Pequeño',
                'Dumoy',
                'Langub',
                'Ma-a',
                'Magtuod',
                'Matina Aplaya',
                'Matina Crossing',
                'Matina Pangi',
                'Talomo Proper',
            ],
            '2nd District' => [
                'Agdao Proper',
                'Centro (San Juan)',
                'Gov. Paciano Bangoy',
                'Gov. Vicente Duterte',
                'Kap. Tomas Monteverde, Sr.',
                'Lapu-Lapu',
                'Leon Garcia',
                'Rafael Castillo',
                'San Antonio',
                'Ubalde',
                'Wilfredo Aquino',
                'Acacia',
                'Alfonso Angliongto Sr.',
                'Buhangin Proper',
                'Cabantian',
                'Callawa',
                'Communal',
                'Indangan',
                'Mandug',
                'Pampanga',
                'Sasa',
                'Tigatto',
                'Vicente Hizon Sr.',
                'Waan',
                'Alejandra Navarro (Lasang)',
                'Bunawan Proper',
                'Gatungan',
                'Ilang',
                'Mahayag',
                'Mudiang',
                'Panacan',
                'San Isidro (Licanan)',
                'Tibungco',
                "Colosas",
                "Fatima (Benowang)",
                "Lumiad",
                "Mabuhay",
                "Malabog",
                "Mapula",
                "Panalum",
                "Pandaitan",
                "Paquibato Proper",
                "Paradise Embak",
                "Salapawan",
                "Sumimao",
                "Tapak",
            ],
            '3rd District' => [
                "Baguio Proper",
                "Cadalian",
                "Carmen",
                "Gumalang",
                "Malagos",
                "Tambobong",
                "Tawan-Tawan",
                "Wines",
                "Biao Joaquin",
                "Calinan Proper",
                "Cawayan",
                "Dacudao",
                "Dalagdag",
                "Dominga",
                "Inayangan",
                "Lacson",
                "Lamanan",
                "Lampianao",
                "Megkawayan",
                "Pangyan",
                "Riverside",
                "Saloy",
                "Sirib",
                "Subasta",
                "Talomo River",
                "Tamayong",
                "Wangan",
                "Baganihan",
                "Bantol",
                "Buda",
                "Dalag",
                "Datu Salumay",
                "Gumitan",
                "Magsaysay",
                "Malamba",
                "Marilog Proper",
                "Salaysay",
                "Suawan (Tuli)",
                "Tamugan",
                "Alambre",
                "Atan-Awe",
                "Bangkas Heights",
                "Baracatan",
                "Bato",
                "Bayabas",
                "Binugao",
                "Camansi",
                "Catigan",
                "Crossing Bayabas",
                "Daliao",
                "Daliaon Plantation",
                "Eden",
                "Kilate",
                "Lizada",
                "Lubogan",
                "Marapangi",
                "Mulig",
                "Sibulan",
                "Sirawan",
                "Tagluno",
                "Tagurano",
                "Tibuloy",
                "Toril Proper",
                "Tungkalan",
                "Angalan",
                "Bago Oshiro",
                "Balenggaeng",
                "Biao Escuela",
                "Biao Guinga",
                "Los Amigos",
                "Manambulan",
                "Manuel Guianga",
                "Matina Biao",
                "Mintal",
                "New Carmen",
                "New Valencia",
                "Santo Niño",
                "Tacunan",
                "Tagakpan",
                "Talandang",
                "Tugbok Proper",
                "Ula"
            ],
        ];

        return $barangayList[$district] ?? [];
    }

    protected function checkSpouse($civil_status, $sex, $nameType, $last_name = null)
    {
        $name = null;
        if (strtolower($civil_status) == 'married') {
            switch ($nameType) {
                case 'first':
                    if (strtolower($sex) == 'male') {
                        return $name = fake()->randomElement([
                            'Andres',
                            'Antonio',
                            'Angelo',
                            'Aldrin',
                            'Albert',
                            'Armando',
                            'Alfonso',
                            'Alex',
                            'Ariel',
                            'Arturo',
                            'Benito',
                            'Bernardo',
                            'Baltazar',
                            'Bartolome',
                            'Benedicto',
                            'Benjamin',
                            'Berto',
                            'Bonifacio',
                            'Bayani',
                            'Basilio',
                            'Carlos',
                            'Cristobal',
                            'Casimir',
                            'Clemente',
                            'Claro',
                            'Celestino',
                            'Cesar',
                            'Cirilo',
                            'Cornelio',
                            'Calixto',
                            'Domingo',
                            'Diosdado',
                            'Diego',
                            'Delfin',
                            'Dante',
                            'Dionisio',
                            'Danilo',
                            'Damaso',
                            'Daniel',
                            'Darwin',
                            'Emilio',
                            'Enrique',
                            'Eduardo',
                            'Esteban',
                            'Eusebio',
                            'Efren',
                            'Eleuterio',
                            'Eliseo',
                            'Ely',
                            'Epifanio',
                            'Federico',
                            'Fernando',
                            'Florante',
                            'Feliciano',
                            'Francisco',
                            'Felipe',
                            'Fabio',
                            'Florencio',
                            'Fortunato',
                            'Fausto',
                            'Gregorio',
                            'Gabriel',
                            'Gerardo',
                            'Gonzalo',
                            'Gavino',
                            'Gilberto',
                            'Generoso',
                            'Geronimo',
                            'Gaudencio',
                            'Gil',
                            'Hector',
                            'Hilario',
                            'Hernando',
                            'Honesto',
                            'Hermogenes',
                            'Huberto',
                            'Haribon',
                            'Hermoso',
                            'Hilarion',
                            'Homer',
                            'Ignacio',
                            'Isidro',
                            'Ireneo',
                            'Irwin',
                            'Ismael',
                            'Isko',
                            'Ibarra',
                            'Igor',
                            'Jose',
                            'Juan',
                            'Julio',
                            'Justo',
                            'Javier',
                            'Jacinto',
                            'Jovito',
                            'Jethro',
                            'Jomar',
                            'Jericho',
                            'Kiko',
                            'Kaleb',
                            'Kian',
                            'Kulas',
                            'Kristoff',
                            'Kimo',
                            'Kian',
                            'Kaden',
                            'Kean',
                            'Kiyoshi',
                            'Luis',
                            'Leonardo',
                            'Lorenzo',
                            'Lamberto',
                            'Lando',
                            'Lito',
                            'Leonel',
                            'Lavrenti',
                            'Larry',
                            'Lakan',
                            'Manuel',
                            'Marcelo',
                            'Mariano',
                            'Mateo',
                            'Maximo',
                            'Melchor',
                            'Modesto',
                            'Macario',
                            'Martin',
                            'Matias',
                            'Nicolas',
                            'Nestor',
                            'Norberto',
                            'Narciso',
                            'Noel',
                            'Nelson',
                            'Nereo',
                            'Natanael',
                            'Napoleon',
                            'Oscar',
                            'Orlando',
                            'Octavio',
                            'Onofre',
                            'Obet',
                            'Osmundo',
                            'Otoniel',
                            'Oliver',
                            'Odilon',
                            'Orlan',
                            'Pedro',
                            'Pablo',
                            'Patricio',
                            'Panfilo',
                            'Primo',
                            'Percival',
                            'Placido',
                            'Paolo',
                            'Porfirio',
                            'Pepito',
                            'Quirino',
                            'Quirico',
                            'Quinito',
                            'Quicho',
                            'Quilo',
                            'Quimby',
                            'Quixote',
                            'Quino',
                            'Querubin',
                            'Quasimodo',
                            'Rafael',
                            'Ramon',
                            'Rodrigo',
                            'Reynaldo',
                            'Rolando',
                            'Romeo',
                            'Rizal',
                            'Rogelio',
                            'Ruben',
                            'Rodolfo',
                            'Santiago',
                            'Salvador',
                            'Severino',
                            'Simeon',
                            'Silverio',
                            'Saturnino',
                            'Sandro',
                            'Solomon',
                            'Sigfredo',
                            'Sylvestre',
                            'Tomas',
                            'Teodoro',
                            'Tito',
                            'Tiburcio',
                            'Tayo',
                            'Tacio',
                            'Tadeo',
                            'Talib',
                            'Tano',
                            'Teyo',
                            'Urbano',
                            'Uriel',
                            'Ulysses',
                            'Ulrich',
                            'Uziel',
                            'Ulan',
                            'Ubay',
                            'Urdaneta',
                            'Ubaldo',
                            'Umberto',
                            'Vicente',
                            'Valerio',
                            'Victor',
                            'Vincent',
                            'Venancio',
                            'Valentino',
                            'Venusto',
                            'Venerando',
                            'Valeriano',
                            'Val',
                            'Waldo',
                            'Wenceslao',
                            'Waldo',
                            'Wally',
                            'Wilson',
                            'Wendell',
                            'Wilfredo',
                            'Winston',
                            'Xavier',
                            'Xandro',
                            'Xian',
                            'Xenon',
                            'Xeres',
                            'Xebastian',
                            'Xian',
                            'Xander',
                            'Yvan',
                            'Ysmael',
                            'Ygor',
                            'Yoel',
                            'Yusuf',
                            'Yvonne',
                            'Yuri',
                            'Yzrael',
                            'Yen',
                            'Yago',
                            'Ymer',
                            'Yael',
                            'Zacarias',
                            'Zaldy',
                            'Ziggy',
                            'Zeus',
                            'Zosimo',
                            'Zenon',
                            'Zander',
                            'Zandro',
                            'Zack',
                            'Zandro',
                            'Zane',
                            'Zosimo'
                        ]);
                    } else if (strtolower($sex) == 'female') {
                        return $name = fake()->randomElement([
                            'Andrea',
                            'Angela',
                            'Adelina',
                            'Aria',
                            'Anabella',
                            'Amara',
                            'Araceli',
                            'Antonia',
                            'Althea',
                            'Amihan',
                            'Beatriz',
                            'Bernadette',
                            'Belinda',
                            'Bambi',
                            'Basilia',
                            'Bonita',
                            'Biance',
                            'Benjamina',
                            'Brenda',
                            'Bethany',
                            'Carmela',
                            'Clarissa',
                            'Camila',
                            'Corazon',
                            'Celestina',
                            'Catherine',
                            'Cecilia',
                            'Catalina',
                            'Chona',
                            'Cristeta',
                            'Diana',
                            'Dianne',
                            'Dahlia',
                            'Delfina',
                            'Divina',
                            'Dominique',
                            'Darlene',
                            'Dalisay',
                            'Danica',
                            'Darcy',
                            'Elena',
                            'Estrella',
                            'Eloisa',
                            'Esperanza',
                            'Editha',
                            'Evangeline',
                            'Eulalia',
                            'Eunice',
                            'Elvira',
                            'Elisa',
                            'Felicia',
                            'Francesca',
                            'Filomena',
                            'Faye',
                            'Fatima',
                            'Florante',
                            'Flordeliza',
                            'Feona',
                            'Febe',
                            'Felicity',
                            'Gabriela',
                            'Guadalupe',
                            'Giselle',
                            'Greta',
                            'Gwendolyn',
                            'Glenda',
                            'Gemma',
                            'Graciela',
                            'Galadriel',
                            'Giana',
                            'Hazel',
                            'Helene',
                            'Hortensia',
                            'Hera',
                            'Harriet',
                            'Hilda',
                            'Hannelore',
                            'Hildegard',
                            'Herminia',
                            'Henrietta',
                            'Imelda',
                            'Isabella',
                            'Ines',
                            'Iliana',
                            'Isha',
                            'Iluminada',
                            'Iara',
                            'Ilang-Ilang',
                            'Isidora',
                            'Idania',
                            'Josefina',
                            'Juanita',
                            'Juliana',
                            'Jocelyn',
                            'Jolina',
                            'Jacinta',
                            'Karina',
                            'Kristina',
                            'Katrina',
                            'Kalista',
                            'Kareen',
                            'Keziah',
                            'Kayla',
                            'Kassandra',
                            'Kiana',
                            'Kimmy',
                            'Lourdes',
                            'Leonora',
                            'Lorena',
                            'Luzviminda',
                            'Luningning',
                            'Leticia',
                            'Lolita',
                            'Laurencia',
                            'Leilani',
                            'Lilybeth',
                            'Maria',
                            'Marissa',
                            'Magdalena',
                            'Magnolia',
                            'Milagros',
                            'Melinda',
                            'Marcela',
                            'Maricar',
                            'Manuela',
                            'Myrna',
                            'Natalia',
                            'Norma',
                            'Nerissa',
                            'Ninfa',
                            'Naomi',
                            'Nydia',
                            'Nenita',
                            'Nelia',
                            'Nieves',
                            'Olivia',
                            'Ophelia',
                            'Ofelia',
                            'Orlinda',
                            'Orquidea',
                            'Odelia',
                            'Octavia',
                            'Omaira',
                            'Osmilda',
                            'Osita',
                            'Patricia',
                            'Priscilla',
                            'Paz',
                            'Perlita',
                            'Pilar',
                            'Paloma',
                            'Paulina',
                            'Paula',
                            'Penelope',
                            'Perla',
                            'Queenie',
                            'Quenby',
                            'Quirina',
                            'Quirita',
                            'Quimberly',
                            'Quenita',
                            'Quirita',
                            'Quenicia',
                            'Quinna',
                            'Quenelle',
                            'Rosalinda',
                            'Rowena',
                            'Remedios',
                            'Regina',
                            'Ruby',
                            'Racquel',
                            'Rizalina',
                            'Rosanna',
                            'Rosita',
                            'Rina',
                            'Solita',
                            'Seraphina',
                            'Soledad',
                            'Salvacion',
                            'Socorro',
                            'Susana',
                            'Sylvia',
                            'Sachi',
                            'Samara',
                            'Selena',
                            'Teresa',
                            'Trinidad',
                            'Tala',
                            'Thelma',
                            'Tintin',
                            'Tisay',
                            'Tessie',
                            'Tatiana',
                            'Tala',
                            'Ursula',
                            'Ulyssa',
                            'Ula',
                            'Ulrica',
                            'Ume',
                            'Urbana',
                            'Valeria',
                            'Veronica',
                            'Violeta',
                            'Venus',
                            'Vanessa',
                            'Viviana',
                            'Vilma',
                            'Wanda',
                            'Wilhelmina',
                            'Winnie',
                            'Wilma',
                            'Winda',
                            'Xenia',
                            'Ximena',
                            'Xochitl',
                            'Xandra',
                            'Yolanda',
                            'Ysabel',
                            'Yvonne',
                            'Yvanna',
                            'Ysabelle',
                            'Yvette',
                            'Yazmin',
                            'Ysolde',
                            'Ynez',
                            'Zenaida',
                            'Zorayda',
                            'Zelia',
                            'Zita',
                            'Zarina',
                            'Zyra',
                            'Zarah',
                            'Zennia',
                            'Zena',
                            'Zenaida',
                            'Zosima'
                        ]);
                    }
                case 'middle':
                    return $name = $this->getMiddleName();
                case 'last':
                    return $name = $last_name;
                case 'ext':
                    return $name = $this->getSuffix();
            }
        }
        return $name;
    }
    protected function getFirstName($sex)
    {
        $firstNames = null;
        if ($sex === 'male') {
            $firstNames = fake()->randomElement([
                'Andres',
                'Antonio',
                'Angelo',
                'Aldrin',
                'Albert',
                'Armando',
                'Alfonso',
                'Alex',
                'Ariel',
                'Arturo',
                'Benito',
                'Bernardo',
                'Baltazar',
                'Bartolome',
                'Benedicto',
                'Benjamin',
                'Berto',
                'Bonifacio',
                'Bayani',
                'Basilio',
                'Carlos',
                'Cristobal',
                'Casimir',
                'Clemente',
                'Claro',
                'Celestino',
                'Cesar',
                'Cirilo',
                'Cornelio',
                'Calixto',
                'Domingo',
                'Diosdado',
                'Diego',
                'Delfin',
                'Dante',
                'Dionisio',
                'Danilo',
                'Damaso',
                'Daniel',
                'Darwin',
                'Emilio',
                'Enrique',
                'Eduardo',
                'Esteban',
                'Eusebio',
                'Efren',
                'Eleuterio',
                'Eliseo',
                'Ely',
                'Epifanio',
                'Federico',
                'Fernando',
                'Florante',
                'Feliciano',
                'Francisco',
                'Felipe',
                'Fabio',
                'Florencio',
                'Fortunato',
                'Fausto',
                'Gregorio',
                'Gabriel',
                'Gerardo',
                'Gonzalo',
                'Gavino',
                'Gilberto',
                'Generoso',
                'Geronimo',
                'Gaudencio',
                'Gil',
                'Hector',
                'Hilario',
                'Hernando',
                'Honesto',
                'Hermogenes',
                'Huberto',
                'Haribon',
                'Hermoso',
                'Hilarion',
                'Homer',
                'Ignacio',
                'Isidro',
                'Ireneo',
                'Irwin',
                'Ismael',
                'Isko',
                'Ibarra',
                'Igor',
                'Jose',
                'Juan',
                'Julio',
                'Justo',
                'Javier',
                'Jacinto',
                'Jovito',
                'Jethro',
                'Jomar',
                'Jericho',
                'Kiko',
                'Kaleb',
                'Kian',
                'Kulas',
                'Kristoff',
                'Kimo',
                'Kian',
                'Kaden',
                'Kean',
                'Kiyoshi',
                'Luis',
                'Leonardo',
                'Lorenzo',
                'Lamberto',
                'Lando',
                'Lito',
                'Leonel',
                'Lavrenti',
                'Larry',
                'Lakan',
                'Manuel',
                'Marcelo',
                'Mariano',
                'Mateo',
                'Maximo',
                'Melchor',
                'Modesto',
                'Macario',
                'Martin',
                'Matias',
                'Nicolas',
                'Nestor',
                'Norberto',
                'Narciso',
                'Noel',
                'Nelson',
                'Nereo',
                'Natanael',
                'Napoleon',
                'Oscar',
                'Orlando',
                'Octavio',
                'Onofre',
                'Obet',
                'Osmundo',
                'Otoniel',
                'Oliver',
                'Odilon',
                'Orlan',
                'Pedro',
                'Pablo',
                'Patricio',
                'Panfilo',
                'Primo',
                'Percival',
                'Placido',
                'Paolo',
                'Porfirio',
                'Pepito',
                'Quirino',
                'Quirico',
                'Quinito',
                'Quicho',
                'Quilo',
                'Quimby',
                'Quixote',
                'Quino',
                'Querubin',
                'Quasimodo',
                'Rafael',
                'Ramon',
                'Rodrigo',
                'Reynaldo',
                'Rolando',
                'Romeo',
                'Rizal',
                'Rogelio',
                'Ruben',
                'Rodolfo',
                'Santiago',
                'Salvador',
                'Severino',
                'Simeon',
                'Silverio',
                'Saturnino',
                'Sandro',
                'Solomon',
                'Sigfredo',
                'Sylvestre',
                'Tomas',
                'Teodoro',
                'Tito',
                'Tiburcio',
                'Tayo',
                'Tacio',
                'Tadeo',
                'Talib',
                'Tano',
                'Teyo',
                'Urbano',
                'Uriel',
                'Ulysses',
                'Ulrich',
                'Uziel',
                'Ulan',
                'Ubay',
                'Urdaneta',
                'Ubaldo',
                'Umberto',
                'Vicente',
                'Valerio',
                'Victor',
                'Vincent',
                'Venancio',
                'Valentino',
                'Venusto',
                'Venerando',
                'Valeriano',
                'Val',
                'Waldo',
                'Wenceslao',
                'Waldo',
                'Wally',
                'Wilson',
                'Wendell',
                'Wilfredo',
                'Winston',
                'Xavier',
                'Xandro',
                'Xian',
                'Xenon',
                'Xeres',
                'Xebastian',
                'Xian',
                'Xander',
                'Yvan',
                'Ysmael',
                'Ygor',
                'Yoel',
                'Yusuf',
                'Yvonne',
                'Yuri',
                'Yzrael',
                'Yen',
                'Yago',
                'Ymer',
                'Yael',
                'Zacarias',
                'Zaldy',
                'Ziggy',
                'Zeus',
                'Zosimo',
                'Zenon',
                'Zander',
                'Zandro',
                'Zack',
                'Zandro',
                'Zane',
                'Zosimo'
            ]);
        } else {
            $firstNames = fake()->randomElement([
                'Andrea',
                'Angela',
                'Adelina',
                'Aria',
                'Anabella',
                'Amara',
                'Araceli',
                'Antonia',
                'Althea',
                'Amihan',
                'Beatriz',
                'Bernadette',
                'Belinda',
                'Bambi',
                'Basilia',
                'Bonita',
                'Biance',
                'Benjamina',
                'Brenda',
                'Bethany',
                'Carmela',
                'Clarissa',
                'Camila',
                'Corazon',
                'Celestina',
                'Catherine',
                'Cecilia',
                'Catalina',
                'Chona',
                'Cristeta',
                'Diana',
                'Dianne',
                'Dahlia',
                'Delfina',
                'Divina',
                'Dominique',
                'Darlene',
                'Dalisay',
                'Danica',
                'Darcy',
                'Elena',
                'Estrella',
                'Eloisa',
                'Esperanza',
                'Editha',
                'Evangeline',
                'Eulalia',
                'Eunice',
                'Elvira',
                'Elisa',
                'Felicia',
                'Francesca',
                'Filomena',
                'Faye',
                'Fatima',
                'Florante',
                'Flordeliza',
                'Feona',
                'Febe',
                'Felicity',
                'Gabriela',
                'Guadalupe',
                'Giselle',
                'Greta',
                'Gwendolyn',
                'Glenda',
                'Gemma',
                'Graciela',
                'Galadriel',
                'Giana',
                'Hazel',
                'Helene',
                'Hortensia',
                'Hera',
                'Harriet',
                'Hilda',
                'Hannelore',
                'Hildegard',
                'Herminia',
                'Henrietta',
                'Imelda',
                'Isabella',
                'Ines',
                'Iliana',
                'Isha',
                'Iluminada',
                'Iara',
                'Ilang-Ilang',
                'Isidora',
                'Idania',
                'Josefina',
                'Juanita',
                'Juliana',
                'Jocelyn',
                'Jolina',
                'Jacinta',
                'Karina',
                'Kristina',
                'Katrina',
                'Kalista',
                'Kareen',
                'Keziah',
                'Kayla',
                'Kassandra',
                'Kiana',
                'Kimmy',
                'Lourdes',
                'Leonora',
                'Lorena',
                'Luzviminda',
                'Luningning',
                'Leticia',
                'Lolita',
                'Laurencia',
                'Leilani',
                'Lilybeth',
                'Maria',
                'Marissa',
                'Magdalena',
                'Magnolia',
                'Milagros',
                'Melinda',
                'Marcela',
                'Maricar',
                'Manuela',
                'Myrna',
                'Natalia',
                'Norma',
                'Nerissa',
                'Ninfa',
                'Naomi',
                'Nydia',
                'Nenita',
                'Nelia',
                'Nieves',
                'Olivia',
                'Ophelia',
                'Ofelia',
                'Orlinda',
                'Orquidea',
                'Odelia',
                'Octavia',
                'Omaira',
                'Osmilda',
                'Osita',
                'Patricia',
                'Priscilla',
                'Paz',
                'Perlita',
                'Pilar',
                'Paloma',
                'Paulina',
                'Paula',
                'Penelope',
                'Perla',
                'Queenie',
                'Quenby',
                'Quirina',
                'Quirita',
                'Quimberly',
                'Quenita',
                'Quirita',
                'Quenicia',
                'Quinna',
                'Quenelle',
                'Rosalinda',
                'Rowena',
                'Remedios',
                'Regina',
                'Ruby',
                'Racquel',
                'Rizalina',
                'Rosanna',
                'Rosita',
                'Rina',
                'Solita',
                'Seraphina',
                'Soledad',
                'Salvacion',
                'Socorro',
                'Susana',
                'Sylvia',
                'Sachi',
                'Samara',
                'Selena',
                'Teresa',
                'Trinidad',
                'Tala',
                'Thelma',
                'Tintin',
                'Tisay',
                'Tessie',
                'Tatiana',
                'Tala',
                'Ursula',
                'Ulyssa',
                'Ula',
                'Ulrica',
                'Ume',
                'Urbana',
                'Valeria',
                'Veronica',
                'Violeta',
                'Venus',
                'Vanessa',
                'Viviana',
                'Vilma',
                'Wanda',
                'Wilhelmina',
                'Winnie',
                'Wilma',
                'Winda',
                'Xenia',
                'Ximena',
                'Xochitl',
                'Xandra',
                'Yolanda',
                'Ysabel',
                'Yvonne',
                'Yvanna',
                'Ysabelle',
                'Yvette',
                'Yazmin',
                'Ysolde',
                'Ynez',
                'Zenaida',
                'Zorayda',
                'Zelia',
                'Zita',
                'Zarina',
                'Zyra',
                'Zarah',
                'Zennia',
                'Zena',
                'Zenaida',
                'Zosima'
            ]);
        }

        $pickedFirstNames = $firstNames;

        $randomNumber = mt_rand(1, 10);
        if ($randomNumber % 2 === 1) {
            if ($sex === 'male') {
                $firstNames = fake()->randomElement([
                    'Andres',
                    'Antonio',
                    'Angelo',
                    'Aldrin',
                    'Albert',
                    'Armando',
                    'Alfonso',
                    'Alex',
                    'Ariel',
                    'Arturo',
                    'Benito',
                    'Bernardo',
                    'Baltazar',
                    'Bartolome',
                    'Benedicto',
                    'Benjamin',
                    'Berto',
                    'Bonifacio',
                    'Bayani',
                    'Basilio',
                    'Carlos',
                    'Cristobal',
                    'Casimir',
                    'Clemente',
                    'Claro',
                    'Celestino',
                    'Cesar',
                    'Cirilo',
                    'Cornelio',
                    'Calixto',
                    'Domingo',
                    'Diosdado',
                    'Diego',
                    'Delfin',
                    'Dante',
                    'Dionisio',
                    'Danilo',
                    'Damaso',
                    'Daniel',
                    'Darwin',
                    'Emilio',
                    'Enrique',
                    'Eduardo',
                    'Esteban',
                    'Eusebio',
                    'Efren',
                    'Eleuterio',
                    'Eliseo',
                    'Ely',
                    'Epifanio',
                    'Federico',
                    'Fernando',
                    'Florante',
                    'Feliciano',
                    'Francisco',
                    'Felipe',
                    'Fabio',
                    'Florencio',
                    'Fortunato',
                    'Fausto',
                    'Gregorio',
                    'Gabriel',
                    'Gerardo',
                    'Gonzalo',
                    'Gavino',
                    'Gilberto',
                    'Generoso',
                    'Geronimo',
                    'Gaudencio',
                    'Gil',
                    'Hector',
                    'Hilario',
                    'Hernando',
                    'Honesto',
                    'Hermogenes',
                    'Huberto',
                    'Haribon',
                    'Hermoso',
                    'Hilarion',
                    'Homer',
                    'Ignacio',
                    'Isidro',
                    'Ireneo',
                    'Irwin',
                    'Ismael',
                    'Isko',
                    'Ibarra',
                    'Igor',
                    'Jose',
                    'Juan',
                    'Julio',
                    'Justo',
                    'Javier',
                    'Jacinto',
                    'Jovito',
                    'Jethro',
                    'Jomar',
                    'Jericho',
                    'Kiko',
                    'Kaleb',
                    'Kian',
                    'Kulas',
                    'Kristoff',
                    'Kimo',
                    'Kian',
                    'Kaden',
                    'Kean',
                    'Kiyoshi',
                    'Luis',
                    'Leonardo',
                    'Lorenzo',
                    'Lamberto',
                    'Lando',
                    'Lito',
                    'Leonel',
                    'Lavrenti',
                    'Larry',
                    'Lakan',
                    'Manuel',
                    'Marcelo',
                    'Mariano',
                    'Mateo',
                    'Maximo',
                    'Melchor',
                    'Modesto',
                    'Macario',
                    'Martin',
                    'Matias',
                    'Nicolas',
                    'Nestor',
                    'Norberto',
                    'Narciso',
                    'Noel',
                    'Nelson',
                    'Nereo',
                    'Natanael',
                    'Napoleon',
                    'Oscar',
                    'Orlando',
                    'Octavio',
                    'Onofre',
                    'Obet',
                    'Osmundo',
                    'Otoniel',
                    'Oliver',
                    'Odilon',
                    'Orlan',
                    'Pedro',
                    'Pablo',
                    'Patricio',
                    'Panfilo',
                    'Primo',
                    'Percival',
                    'Placido',
                    'Paolo',
                    'Porfirio',
                    'Pepito',
                    'Quirino',
                    'Quirico',
                    'Quinito',
                    'Quicho',
                    'Quilo',
                    'Quimby',
                    'Quixote',
                    'Quino',
                    'Querubin',
                    'Quasimodo',
                    'Rafael',
                    'Ramon',
                    'Rodrigo',
                    'Reynaldo',
                    'Rolando',
                    'Romeo',
                    'Rizal',
                    'Rogelio',
                    'Ruben',
                    'Rodolfo',
                    'Santiago',
                    'Salvador',
                    'Severino',
                    'Simeon',
                    'Silverio',
                    'Saturnino',
                    'Sandro',
                    'Solomon',
                    'Sigfredo',
                    'Sylvestre',
                    'Tomas',
                    'Teodoro',
                    'Tito',
                    'Tiburcio',
                    'Tayo',
                    'Tacio',
                    'Tadeo',
                    'Talib',
                    'Tano',
                    'Teyo',
                    'Urbano',
                    'Uriel',
                    'Ulysses',
                    'Ulrich',
                    'Uziel',
                    'Ulan',
                    'Ubay',
                    'Urdaneta',
                    'Ubaldo',
                    'Umberto',
                    'Vicente',
                    'Valerio',
                    'Victor',
                    'Vincent',
                    'Venancio',
                    'Valentino',
                    'Venusto',
                    'Venerando',
                    'Valeriano',
                    'Val',
                    'Waldo',
                    'Wenceslao',
                    'Waldo',
                    'Wally',
                    'Wilson',
                    'Wendell',
                    'Wilfredo',
                    'Winston',
                    'Xavier',
                    'Xandro',
                    'Xian',
                    'Xenon',
                    'Xeres',
                    'Xebastian',
                    'Xian',
                    'Xander',
                    'Yvan',
                    'Ysmael',
                    'Ygor',
                    'Yoel',
                    'Yusuf',
                    'Yvonne',
                    'Yuri',
                    'Yzrael',
                    'Yen',
                    'Yago',
                    'Ymer',
                    'Yael',
                    'Zacarias',
                    'Zaldy',
                    'Ziggy',
                    'Zeus',
                    'Zosimo',
                    'Zenon',
                    'Zander',
                    'Zandro',
                    'Zack',
                    'Zandro',
                    'Zane',
                    'Zosimo'
                ]);
            } else {
                $firstNames = fake()->randomElement([
                    'Andrea',
                    'Angela',
                    'Adelina',
                    'Aria',
                    'Anabella',
                    'Amara',
                    'Araceli',
                    'Antonia',
                    'Althea',
                    'Amihan',
                    'Beatriz',
                    'Bernadette',
                    'Belinda',
                    'Bambi',
                    'Basilia',
                    'Bonita',
                    'Biance',
                    'Benjamina',
                    'Brenda',
                    'Bethany',
                    'Carmela',
                    'Clarissa',
                    'Camila',
                    'Corazon',
                    'Celestina',
                    'Catherine',
                    'Cecilia',
                    'Catalina',
                    'Chona',
                    'Cristeta',
                    'Diana',
                    'Dianne',
                    'Dahlia',
                    'Delfina',
                    'Divina',
                    'Dominique',
                    'Darlene',
                    'Dalisay',
                    'Danica',
                    'Darcy',
                    'Elena',
                    'Estrella',
                    'Eloisa',
                    'Esperanza',
                    'Editha',
                    'Evangeline',
                    'Eulalia',
                    'Eunice',
                    'Elvira',
                    'Elisa',
                    'Felicia',
                    'Francesca',
                    'Filomena',
                    'Faye',
                    'Fatima',
                    'Florante',
                    'Flordeliza',
                    'Feona',
                    'Febe',
                    'Felicity',
                    'Gabriela',
                    'Guadalupe',
                    'Giselle',
                    'Greta',
                    'Gwendolyn',
                    'Glenda',
                    'Gemma',
                    'Graciela',
                    'Galadriel',
                    'Giana',
                    'Hazel',
                    'Helene',
                    'Hortensia',
                    'Hera',
                    'Harriet',
                    'Hilda',
                    'Hannelore',
                    'Hildegard',
                    'Herminia',
                    'Henrietta',
                    'Imelda',
                    'Isabella',
                    'Ines',
                    'Iliana',
                    'Isha',
                    'Iluminada',
                    'Iara',
                    'Ilang-Ilang',
                    'Isidora',
                    'Idania',
                    'Josefina',
                    'Juanita',
                    'Juliana',
                    'Jocelyn',
                    'Jolina',
                    'Jacinta',
                    'Karina',
                    'Kristina',
                    'Katrina',
                    'Kalista',
                    'Kareen',
                    'Keziah',
                    'Kayla',
                    'Kassandra',
                    'Kiana',
                    'Kimmy',
                    'Lourdes',
                    'Leonora',
                    'Lorena',
                    'Luzviminda',
                    'Luningning',
                    'Leticia',
                    'Lolita',
                    'Laurencia',
                    'Leilani',
                    'Lilybeth',
                    'Maria',
                    'Marissa',
                    'Magdalena',
                    'Magnolia',
                    'Milagros',
                    'Melinda',
                    'Marcela',
                    'Maricar',
                    'Manuela',
                    'Myrna',
                    'Natalia',
                    'Norma',
                    'Nerissa',
                    'Ninfa',
                    'Naomi',
                    'Nydia',
                    'Nenita',
                    'Nelia',
                    'Nieves',
                    'Olivia',
                    'Ophelia',
                    'Ofelia',
                    'Orlinda',
                    'Orquidea',
                    'Odelia',
                    'Octavia',
                    'Omaira',
                    'Osmilda',
                    'Osita',
                    'Patricia',
                    'Priscilla',
                    'Paz',
                    'Perlita',
                    'Pilar',
                    'Paloma',
                    'Paulina',
                    'Paula',
                    'Penelope',
                    'Perla',
                    'Queenie',
                    'Quenby',
                    'Quirina',
                    'Quirita',
                    'Quimberly',
                    'Quenita',
                    'Quirita',
                    'Quenicia',
                    'Quinna',
                    'Quenelle',
                    'Rosalinda',
                    'Rowena',
                    'Remedios',
                    'Regina',
                    'Ruby',
                    'Racquel',
                    'Rizalina',
                    'Rosanna',
                    'Rosita',
                    'Rina',
                    'Solita',
                    'Seraphina',
                    'Soledad',
                    'Salvacion',
                    'Socorro',
                    'Susana',
                    'Sylvia',
                    'Sachi',
                    'Samara',
                    'Selena',
                    'Teresa',
                    'Trinidad',
                    'Tala',
                    'Thelma',
                    'Tintin',
                    'Tisay',
                    'Tessie',
                    'Tatiana',
                    'Tala',
                    'Ursula',
                    'Ulyssa',
                    'Ula',
                    'Ulrica',
                    'Ume',
                    'Urbana',
                    'Valeria',
                    'Veronica',
                    'Violeta',
                    'Venus',
                    'Vanessa',
                    'Viviana',
                    'Vilma',
                    'Wanda',
                    'Wilhelmina',
                    'Winnie',
                    'Wilma',
                    'Winda',
                    'Xenia',
                    'Ximena',
                    'Xochitl',
                    'Xandra',
                    'Yolanda',
                    'Ysabel',
                    'Yvonne',
                    'Yvanna',
                    'Ysabelle',
                    'Yvette',
                    'Yazmin',
                    'Ysolde',
                    'Ynez',
                    'Zenaida',
                    'Zorayda',
                    'Zelia',
                    'Zita',
                    'Zarina',
                    'Zyra',
                    'Zarah',
                    'Zennia',
                    'Zena',
                    'Zenaida',
                    'Zosima'
                ]);
            }
            $pickedFirstNames .= ' ' . $firstNames;
        }

        return $pickedFirstNames;
    }

    protected function getLastName()
    {
        return fake()->randomElement([
            'Abad',
            'Abalos',
            'Abdullah',
            'Abdul',
            'Abella',
            'Acuña',
            'Acosta',
            'Adriano',
            'Agustin',
            'Aguilar',
            'Aguirre',
            'Alba',
            'Alcantara',
            'Alejandro',
            'Ali',
            'Alonzo',
            'Alvarez',
            'Alvarado',
            'Alfonso',
            'Alba',
            'Alcantara',
            'Alejandro',
            'Ali',
            'Alonzo',
            'Alvarez',
            'Andaya',
            'Andres',
            'Andrade',
            'Ang',
            'Angeles',
            'Anonuevo',
            'Antonio',
            'Aquino',
            'Arellano',
            'Arevalo',
            'Apostol',
            'Arcilla',
            'Aragon',
            'Arroyo',
            'Asis',
            'Asuncion',
            'Austria',
            'Avila',
            'Baguio',
            'Baltazar',
            'Ballesteros',
            'Basa',
            'Basco',
            'Basilio',
            'Bartolome',
            'Barrientos',
            'Bautista',
            'Baylon',
            'Beltran',
            'Bello',
            'Benitez',
            'Bernabe',
            'Bernal',
            'Bernardo',
            'Blanco',
            'Bondoc',
            'Bonifacio',
            'Borja',
            'Borromeo',
            'Bravo',
            'Briones',
            'Buenaventura',
            'Bueno',
            'Bustamante',
            'Caballero',
            'Cabrera',
            'Cabral',
            'Calderon',
            'Calma',
            'Camacho',
            'Canete',
            'Canlas',
            'Canoy',
            'Carino',
            'Carpio',
            'Carlos',
            'Castaneda',
            'Castillo',
            'Castor',
            'Castro',
            'Catalan',
            'Cayabyab',
            'Cervantes',
            'Chan',
            'Chavez',
            'Chua',
            'Clemente',
            'Cordero',
            'Corpus',
            'Concepcion',
            'Constantino',
            'Conde',
            'Cordova',
            'Cortes',
            'Cortez',
            'Collado',
            'Cuizon',
            'Cristobal',
            'Cruz',
            'Custodio',
            'Dela Cruz',
            'Dela Pena',
            'Dela Rosa',
            'Dela Torre',
            'Delgado',
            'Delos Reyes',
            'Delos Santos',
            'Diaz',
            'Dizon',
            'Domingo',
            'Dominguez',
            'Dulay',
            'Duran',
            'Estrada',
            'Espina',
            'Espino',
            'Espiritu',
            'Esguerra',
            'Esteban',
            'Estrella',
            'Evangelista',
            'Fernandez',
            'Fernando',
            'Feliciano',
            'Felipe',
            'Ferrer',
            'Flores',
            'Francisco',
            'Franco',
            'Frias',
            'Fuentes',
            'Gallardo',
            'Galang',
            'Galicia',
            'Gallego',
            'Galvez',
            'Gamboa',
            'Garcia',
            'Gaspar',
            'Geronimo',
            'Gregorio',
            'Gomez',
            'Go',
            'Gonzaga',
            'Gonzales',
            'Guerrero',
            'Gutierrez',
            'Guinto',
            'Guzman',
            'Hilario',
            'Hipolito',
            'Hernandez',
            'Ibanez',
            'Ilagan',
            'Ignacio',
            'Jacinto',
            'Javier',
            'Jimenez',
            'Jose',
            'Juan',
            'Junio',
            'Labrador',
            'Lachica',
            'Lacson',
            'Lara',
            'Laurente',
            'Lazaro',
            'Ledesma',
            'Legaspi',
            'Lim',
            'Lorenzo',
            'Lopez',
            'Lozada',
            'Lucas',
            'Lucero',
            'Luna',
            'Mahinay',
            'Mallari',
            'Manalo',
            'Manansala',
            'Manzano',
            'Marcelo',
            'Marquez',
            'Marasigan',
            'Martinez',
            'Mateo',
            'Mata',
            'Mejia',
            'Medina',
            'Mendez',
            'Mercado',
            'Miranda',
            'Miguel',
            'Molina',
            'Molino',
            'Montero',
            'Morales',
            'Moreno',
            'Muhammad',
            'Munoz',
            'Narciso',
            'Navarro',
            'Natividad',
            'Nicolas',
            'Nunez',
            'Ocampo',
            'Oliva',
            'Omar',
            'Ong',
            'Ortega',
            'Ortiz',
            'Padilla',
            'Palma',
            'Panes',
            'Pangilinan',
            'Pangan',
            'Pascual',
            'Pascua',
            'Peña',
            'Pepito',
            'Perez',
            'Pimentel',
            'Pineda',
            'Ponce',
            'Porras',
            'Prado',
            'Pablo',
            'Quijano',
            'Quinto',
            'Ramirez',
            'Ramos',
            'Ramos',
            'Reyes',
            'Rivera',
            'Rodriguez',
            'Roldan',
            'Romero',
            'Romualdez',
            'Ronquillo',
            'Roxas',
            'Ruedas',
            'Ruiz',
            'Salvador',
            'Salas',
            'Sali',
            'Samonte',
            'Sanchez',
            'Santillan',
            'Santos',
            'Sarmiento',
            'Sebastian',
            'Sebastian',
            'Serrano',
            'Serrano',
            'Solomon',
            'Solis',
            'Solis',
            'Soriano',
            'Suarez',
            'Tomas',
            'Tolentino',
            'Torres',
            'Tuazon',
            'Valdez',
            'Valencia',
            'Valenzuela',
            'Vargas',
            'Velasco',
            'Ventura',
            'Vergara',
            'Vicente',
            'Villa',
            'Villanueva',
            'Villarin',
            'Villamor',
            'Villaflor',
            'Villanueva',
            'Villareal',
            'Yap',
            'Yu',
            'Zamora',
            'Zapanta',
        ]);
    }

    protected function getMiddleName()
    {
        return fake()->optional(0.85)->randomElement([
            'Abad',
            'Abalos',
            'Abdullah',
            'Abdul',
            'Abella',
            'Acuña',
            'Acosta',
            'Adriano',
            'Agustin',
            'Aguilar',
            'Aguirre',
            'Alba',
            'Alcantara',
            'Alejandro',
            'Ali',
            'Alonzo',
            'Alvarez',
            'Alvarado',
            'Alfonso',
            'Alba',
            'Alcantara',
            'Alejandro',
            'Ali',
            'Alonzo',
            'Alvarez',
            'Andaya',
            'Andres',
            'Andrade',
            'Ang',
            'Angeles',
            'Anonuevo',
            'Antonio',
            'Aquino',
            'Arellano',
            'Arevalo',
            'Apostol',
            'Arcilla',
            'Aragon',
            'Arroyo',
            'Asis',
            'Asuncion',
            'Austria',
            'Avila',
            'Baguio',
            'Baltazar',
            'Ballesteros',
            'Basa',
            'Basco',
            'Basilio',
            'Bartolome',
            'Barrientos',
            'Bautista',
            'Baylon',
            'Beltran',
            'Bello',
            'Benitez',
            'Bernabe',
            'Bernal',
            'Bernardo',
            'Blanco',
            'Bondoc',
            'Bonifacio',
            'Borja',
            'Borromeo',
            'Bravo',
            'Briones',
            'Buenaventura',
            'Bueno',
            'Bustamante',
            'Caballero',
            'Cabrera',
            'Cabral',
            'Calderon',
            'Calma',
            'Camacho',
            'Canete',
            'Canlas',
            'Canoy',
            'Carino',
            'Carpio',
            'Carlos',
            'Castaneda',
            'Castillo',
            'Castor',
            'Castro',
            'Catalan',
            'Cayabyab',
            'Cervantes',
            'Chan',
            'Chavez',
            'Chua',
            'Clemente',
            'Cordero',
            'Corpus',
            'Concepcion',
            'Constantino',
            'Conde',
            'Cordova',
            'Cortes',
            'Cortez',
            'Collado',
            'Cuizon',
            'Cristobal',
            'Cruz',
            'Custodio',
            'Dela Cruz',
            'Dela Pena',
            'Dela Rosa',
            'Dela Torre',
            'Delgado',
            'Delos Reyes',
            'Delos Santos',
            'Diaz',
            'Dizon',
            'Domingo',
            'Dominguez',
            'Dulay',
            'Duran',
            'Estrada',
            'Espina',
            'Espino',
            'Espiritu',
            'Esguerra',
            'Esteban',
            'Estrella',
            'Evangelista',
            'Fernandez',
            'Fernando',
            'Feliciano',
            'Felipe',
            'Ferrer',
            'Flores',
            'Francisco',
            'Franco',
            'Frias',
            'Fuentes',
            'Gallardo',
            'Galang',
            'Galicia',
            'Gallego',
            'Galvez',
            'Gamboa',
            'Garcia',
            'Gaspar',
            'Geronimo',
            'Gregorio',
            'Gomez',
            'Go',
            'Gonzaga',
            'Gonzales',
            'Guerrero',
            'Gutierrez',
            'Guinto',
            'Guzman',
            'Hilario',
            'Hipolito',
            'Hernandez',
            'Ibanez',
            'Ilagan',
            'Ignacio',
            'Jacinto',
            'Javier',
            'Jimenez',
            'Jose',
            'Juan',
            'Junio',
            'Labrador',
            'Lachica',
            'Lacson',
            'Lara',
            'Laurente',
            'Lazaro',
            'Ledesma',
            'Legaspi',
            'Lim',
            'Lorenzo',
            'Lopez',
            'Lozada',
            'Lucas',
            'Lucero',
            'Luna',
            'Mahinay',
            'Mallari',
            'Manalo',
            'Manansala',
            'Manzano',
            'Marcelo',
            'Marquez',
            'Marasigan',
            'Martinez',
            'Mateo',
            'Mata',
            'Mejia',
            'Medina',
            'Mendez',
            'Mercado',
            'Miranda',
            'Miguel',
            'Molina',
            'Molino',
            'Montero',
            'Morales',
            'Moreno',
            'Muhammad',
            'Munoz',
            'Narciso',
            'Navarro',
            'Natividad',
            'Nicolas',
            'Nunez',
            'Ocampo',
            'Oliva',
            'Omar',
            'Ong',
            'Ortega',
            'Ortiz',
            'Padilla',
            'Palma',
            'Panes',
            'Pangilinan',
            'Pangan',
            'Pascual',
            'Pascua',
            'Peña',
            'Pepito',
            'Perez',
            'Pimentel',
            'Pineda',
            'Ponce',
            'Porras',
            'Prado',
            'Pablo',
            'Quijano',
            'Quinto',
            'Ramirez',
            'Ramos',
            'Ramos',
            'Reyes',
            'Rivera',
            'Rodriguez',
            'Roldan',
            'Romero',
            'Romualdez',
            'Ronquillo',
            'Roxas',
            'Ruedas',
            'Ruiz',
            'Salvador',
            'Salas',
            'Sali',
            'Samonte',
            'Sanchez',
            'Santillan',
            'Santos',
            'Sarmiento',
            'Sebastian',
            'Sebastian',
            'Serrano',
            'Serrano',
            'Solomon',
            'Solis',
            'Solis',
            'Soriano',
            'Suarez',
            'Tomas',
            'Tolentino',
            'Torres',
            'Tuazon',
            'Valdez',
            'Valencia',
            'Valenzuela',
            'Vargas',
            'Velasco',
            'Ventura',
            'Vergara',
            'Vicente',
            'Villa',
            'Villanueva',
            'Villarin',
            'Villamor',
            'Villaflor',
            'Villanueva',
            'Villareal',
            'Yap',
            'Yu',
            'Zamora',
            'Zapanta',
        ]);
    }

    protected function getSuffix()
    {
        return fake()->optional(0.1)->randomElement(['I', 'II', 'III', 'IV', 'Sr.', 'Jr.']);
    }

    // -----------------------------------
// 
// 
// 
//      Do not uncomment this part
// 
// 
// 
// 
    // -----------------------------------


    // function getTotalBatchesCount()
    // {
    //     $totalBatchesCount = DB::table('batches')->count();
    //     return $totalBatchesCount;
    // }

    // function distributeSlots(): int
    // {
    //     $percentage = (static::$globalTotalSlots / static::$originalTotalSlots) * 100;
    //     // Check if the remaining slots is below a certain threshold
    //     if ($percentage <= 25) {
    //         static::$randBatchAmount = 0;
    //         return 69; // return the remaining slots
    //     }
    //     // The max allocated slots shouldn't exceed more than half of its value
    //     $max = floor(static::$globalTotalSlots * 0.75);
    //     // Generate a random slot allocation ensuring that there are enough slots left for the remaining batches
    //     $slot = rand(10, $max);
    //     static::$globalTotalSlots -= $slot;

    //     return $slot;
    // }
}
