<?php

namespace App\Services;

class Barangays
{
    /**
     *  @param string $city_municipality The selected city/municipality by the user
     *  @param string $district (optional) The selected district by the user
     *  @return string[]|null Returns an array of barangays if true, returns null if false
     */
    public function getBarangays(string $city_municipality, string $district = null): array|null
    {
        $barangays = null;

        # Davao del Sur
        if ($city_municipality === 'Digos City') {
            $barangays = [
                'Aplaya',
                'Balabag',
                'San Jose (Balutakay)',
                'Binaton',
                'Cogon',
                'Colorado',
                'Dawis',
                'Dulangan',
                'Goma',
                'Igpit',
                'Kiagot',
                'Lungag',
                'Mahayahay',
                'Matti',
                'Kapatagan (Rizal)',
                'Ruparan',
                'San Agustin',
                'San Miguel (Odaca)',
                'San Roque',
                'Sinawilan',
                'Soong',
                'Tiguman',
                'Tres De Mayo',
                'Zone 1 (Pob.)',
                'Zone 2 (Pob.)',
                'Zone 3 (Pob.)'
            ];
        } else if ($city_municipality === 'Bansalan') {
            $barangays = [
                'Alegre',
                'Alta Vista',
                'Anonang',
                'Bitaug',
                'Bonifacio',
                'Buenavista',
                'Darapuay',
                'Dolo',
                'Eman',
                'Kinuskusan',
                'Libertad',
                'Linawan',
                'Mabuhay',
                'Mabunga',
                'Managa',
                'Marber',
                'New Clarin',
                'Poblacion Uno',
                'Poblacion Dos',
                'Rizal',
                'Santo Niño',
                'Sibayan',
                'Tinongtongan',
                'Tubod',
                'Union'
            ];
        } else if ($city_municipality === 'Davao City') {
            if ($district === '1st District') {
                $barangays = [
                    '1-A',
                    '2-A',
                    '3-A',
                    '4-A',
                    '5-A',
                    '6-A',
                    '7-A',
                    '8-A',
                    '9-A',
                    '10-A',
                    '11-B',
                    '12-B',
                    '13-B',
                    '14-B',
                    '15-B',
                    '16-B',
                    '17-B',
                    '18-B',
                    '19-B',
                    '20-B',
                    '21-C',
                    '22-C',
                    '23-C',
                    '24-C',
                    '25-C',
                    '26-C',
                    '27-C',
                    '28-C',
                    '29-C',
                    '30-C',
                    '31-D',
                    '32-D',
                    '33-D',
                    '34-D',
                    '35-D',
                    '36-D',
                    '37-D',
                    '38-D',
                    '39-D',
                    '40-D',
                    'Bago Aplaya',
                    'Bago Gallera',
                    'Baliok',
                    'Bucana',
                    'Catalunan Grande',
                    'Catalunan Pequeño',
                    'Dumoy',
                    'Langub',
                    'Ma-a',
                    'Magtuod',
                    'Matina Aplaya',
                    'Matina Crossing',
                    'Matina Pangi',
                    'Talomo Proper',
                ];
            } else if ($district === '2nd District') {
                $barangays = [
                    'Agdao Proper',
                    'Centro (San Juan)',
                    'Gov. Paciano Bangoy',
                    'Gov. Vicente Duterte',
                    'Kap. Tomas Monteverde, Sr.',
                    'Lapu-Lapu',
                    'Leon Garcia',
                    'Rafael Castillo',
                    'San Antonio',
                    'Ubalde',
                    'Wilfredo Aquino',
                    'Acacia',
                    'Alfonso Angliongto Sr.',
                    'Buhangin Proper',
                    'Cabantian',
                    'Callawa',
                    'Communal',
                    'Indangan',
                    'Mandug',
                    'Pampanga',
                    'Sasa',
                    'Tigatto',
                    'Vicente Hizon Sr.',
                    'Waan',
                    'Alejandra Navarro (Lasang)',
                    'Bunawan Proper',
                    'Gatungan',
                    'Ilang',
                    'Mahayag',
                    'Mudiang',
                    'Panacan',
                    'San Isidro (Licanan)',
                    'Tibungco',
                    "Colosas",
                    "Fatima (Benowang)",
                    "Lumiad",
                    "Mabuhay",
                    "Malabog",
                    "Mapula",
                    "Panalum",
                    "Pandaitan",
                    "Paquibato Proper",
                    "Paradise Embak",
                    "Salapawan",
                    "Sumimao",
                    "Tapak",

                ];
            } else if ($district === '3rd District') {
                $barangays = [
                    "Baguio Proper",
                    "Cadalian",
                    "Carmen",
                    "Gumalang",
                    "Malagos",
                    "Tambobong",
                    "Tawan-Tawan",
                    "Wines",
                    "Biao Joaquin",
                    "Calinan Proper",
                    "Cawayan",
                    "Dacudao",
                    "Dalagdag",
                    "Dominga",
                    "Inayangan",
                    "Lacson",
                    "Lamanan",
                    "Lampianao",
                    "Megkawayan",
                    "Pangyan",
                    "Riverside",
                    "Saloy",
                    "Sirib",
                    "Subasta",
                    "Talomo River",
                    "Tamayong",
                    "Wangan",
                    "Baganihan",
                    "Bantol",
                    "Buda",
                    "Dalag",
                    "Datu Salumay",
                    "Gumitan",
                    "Magsaysay",
                    "Malamba",
                    "Marilog Proper",
                    "Salaysay",
                    "Suawan (Tuli)",
                    "Tamugan",
                    "Alambre",
                    "Atan-Awe",
                    "Bangkas Heights",
                    "Baracatan",
                    "Bato",
                    "Bayabas",
                    "Binugao",
                    "Camansi",
                    "Catigan",
                    "Crossing Bayabas",
                    "Daliao",
                    "Daliaon Plantation",
                    "Eden",
                    "Kilate",
                    "Lizada",
                    "Lubogan",
                    "Marapangi",
                    "Mulig",
                    "Sibulan",
                    "Sirawan",
                    "Tagluno",
                    "Tagurano",
                    "Tibuloy",
                    "Toril Proper",
                    "Tungkalan",
                    "Angalan",
                    "Bago Oshiro",
                    "Balenggaeng",
                    "Biao Escuela",
                    "Biao Guinga",
                    "Los Amigos",
                    "Manambulan",
                    "Manuel Guianga",
                    "Matina Biao",
                    "Mintal",
                    "New Carmen",
                    "New Valencia",
                    "Santo Niño",
                    "Tacunan",
                    "Tagakpan",
                    "Talandang",
                    "Tugbok Proper",
                    "Ula"
                ];
            }
        } else if ($city_municipality === 'Hagonoy') {
            $barangays = [
                'Aplaya',
                'Balutakay',
                'Clib',
                'Guihing',
                'Hagonoy Crossing',
                'Kibuaya',
                'La Union',
                'Lanuro',
                'Lapulabao',
                'Leling',
                'Mahayahay',
                'Malabang Damsite',
                'Maliit Digos',
                'New Quezon',
                'Paligue',
                'Poblacion',
                'Sacub',
                'San Guillermo',
                'San Isidro',
                'Sinayawan',
                'Tologan'
            ];
        } else if ($city_municipality === 'Kiblawan') {
            $barangays = [
                'Abnate',
                'Bagong Negros',
                'Bagong Silang',
                'Bagumbayan',
                'Balasiao',
                'Bonifacio',
                'Bunot',
                'Cogon-Bacaca',
                'Dapok',
                'Ihan',
                'Kibongbong',
                'Kimlawis',
                'Kisulan',
                'Lati-an',
                'Manual',
                'Maraga-a',
                'Molopolo',
                'New Sibonga',
                'Panaglib',
                'Pasig',
                'Poblacion',
                'Pocaleel',
                'San Isidro',
                'San Jose',
                'San Pedro',
                'Santo Niño',
                'Tacub',
                'Tacul',
                'Waterfall',
                'Bulol-Salo'
            ];
        } else if ($city_municipality === 'Magsaysay') {
            $barangays = [
                'Bacungan',
                'Balnate',
                'Barayong',
                'Blocon',
                'Dalawinon',
                'Dalumay',
                'Glamang',
                'Kanapulo',
                'Kasuga',
                'Lower Bala',
                'Mabini',
                'Malawanit',
                'Malongon',
                'New Ilocos',
                'Poblacion (Kialeg)',
                'San Isidro',
                'San Miguel',
                'Tacul',
                'Tagaytay',
                'Upper Bala',
                'Maibo',
                'New Opon'
            ];
        } else if ($city_municipality === 'Malalag') {
            $barangays = [
                'Bagumbayan',
                'Baybay',
                'Bolton',
                'Bulacan',
                'Caputian',
                'Ibo',
                'Kiblagon',
                'Lapla',
                'Mabini',
                'New Baclayon',
                'Pitu',
                'Poblacion',
                'Tagansule',
                'Rizal (Parame)',
                'San Isidro'
            ];
        } else if ($city_municipality === 'Matanao') {
            $barangays = [
                'Asbang',
                'Asinan',
                'Bagumbayan',
                'Bangkal',
                'Buas',
                'Buri',
                'Camanchiles',
                'Ceboza',
                'Colonsabak',
                'Dongan-Pekong',
                'Kabasagan',
                'Kapok',
                'Kauswagan',
                'Kibao',
                'La Suerte',
                'Langa-an',
                'Lower Marber',
                'Cabligan (Managa)',
                'Manga',
                'New Katipunan',
                'New Murcia',
                'New Visayas',
                'Poblacion',
                'Saboy',
                'San Jose',
                'San Miguel',
                'San Vicente',
                'Saub',
                'Sinaragan',
                'Sinawilan',
                'Tamlangon',
                'Towak',
                'Tibongbong'
            ];
        } else if ($city_municipality === 'Padada') {
            $barangays = [
                'Almendras (Poblacion)',
                'Don Sergio Osmena, Sr.',
                'Harada Butai',
                'Lower Katipunan',
                'Lower Limonzo',
                'Lower Malinao',
                'N C Ordaneza District (Poblacion)',
                'Northern Paligue',
                'Palili',
                'Piape',
                'Punta Piape',
                'Quirino District (Poblacion)',
                'San Isidro',
                'Southern Paligue',
                'Tulugan',
                'Upper Limonzo',
                'Upper Malinao'
            ];
        } else if ($city_municipality === 'Santa Cruz') {
            $barangays = [
                'Astorga',
                'Bato',
                'Coronon',
                'Darong',
                'Inawayan',
                'Jose Rizal',
                'Matutungan',
                'Melilia',
                'Saliducon',
                'Sibulan',
                'Sinoron',
                'Tagabuli',
                'Tibolo',
                'Tuban',
                'Zone I (Poblacion)',
                'Zone II (Poblacion)',
                'Zone III (Poblacion)',
                'Zone IV (Poblacion)'
            ];
        } else if ($city_municipality === 'Sulop') {
            $barangays = [
                'Balasinon',
                'Buguis',
                'Carre',
                'Clib',
                'Harada Butai',
                'Katipunan',
                'Kiblagon',
                'Labon',
                'Laperas',
                'Lapla',
                'Litos',
                'Luparan',
                'Mckinley',
                'New Cebu',
                'Osmeña',
                'Palili',
                'Parame',
                'Poblacion',
                'Roxas',
                'Solongvale',
                'Tagolilong',
                'Tala-o',
                'Talas',
                'Tanwalang',
                'Waterfall'
            ];
        }

        # Davao de Oro
        if ($city_municipality === 'Nabunturan') {
            $barangays = [
                'Bagongon',
                'Gabi',
                'Lagab',
                'Mangayon',
                'Mapaca',
                'Maparat',
                'New Alegria',
                'Ngan',
                'Osmeña',
                'Panansalan',
                'Poblacion',
                'San Jose',
                'San Miguel',
                'Siocon',
                'Tamia',
                'Aurora'
            ];
        } else if ($city_municipality === 'Compostela') {
            $barangays = [
                'Bagongon',
                'Gabi',
                'Lagab',
                'Mangayon',
                'Mapaca',
                'Maparat',
                'New Alegria',
                'Ngan',
                'Osmeña',
                'Panansalan',
                'Poblacion',
                'San Jose',
                'San Miguel',
                'Siocon',
                'Tamia',
                'Aurora'
            ];
        } else if ($city_municipality === 'Laak') {
            $barangays = [
                'Aguinaldo',
                'Amorcruz',
                'Ampawid',
                'Andap',
                'Anitap',
                'Bagong Silang',
                'Banbanon',
                'Belmonte',
                'Binasbas',
                'Bullucan',
                'Ceboleda',
                'Concepcion',
                'Datu Ampunan',
                'Datu Davao',
                'Doña Josefa',
                'El Katipunan',
                'Il Papa',
                'Imelda',
                'Inakayan',
                'Kaligutan',
                'Kapatagan',
                'Kidawa',
                'Kilagding',
                'Kiokmay',
                'Laak (Poblacion)',
                'Langtud',
                'Longanapan',
                'Mabuhay',
                'Macopa',
                'Malinao',
                'Mangloy',
                'Melale',
                'Naga',
                'New Bethlehem',
                'Panamoren',
                'Sabud',
                'San Antonio',
                'Sta Emilia',
                'Sto Niño',
                'Sisimon'
            ];
        } else if ($city_municipality === 'Mabini') {
            $barangays = [
                'Cadunan',
                'Pindasan',
                'Cuambog (Poblacion)',
                'Tagnanan (Mampising)',
                'Anitapan',
                'Cabuyuan',
                'Del Pilar',
                'Libodon',
                'Golden Valley (Maraut)',
                'Pangibiran',
                'San Antonio'
            ];
        } else if ($city_municipality === 'Maco') {
            $barangays = [
                'Anibongan',
                'Anislagan',
                'Binuangan',
                'Bucana',
                'Calabcab',
                'Concepcion',
                'Dumlan',
                'Elizalde (Somil)',
                'Pangi (Gaudencio Antonio)',
                'Gubatan',
                'Hijo',
                'Kinuban',
                'Langgam',
                'Lapu-lapu',
                'Libay-libay',
                'Limbo',
                'Lumatab',
                'Magangit',
                'Malamodao',
                'Manipongol',
                'Mapaang',
                'Masara',
                'New Asturias',
                'Panibasan',
                'Panoraon',
                'Poblacion',
                'San Juan',
                'San Roque',
                'Sangab',
                'Taglawig',
                'Mainit',
                'New Barili',
                'New Leyte',
                'New Visayas',
                'Panangan',
                'Tagbaros',
                'Teresa'
            ];
        } else if ($city_municipality === 'Maragusan') {
            $barangays = [
                'Bagong Silang',
                'Mapawa',
                'Maragusan (Poblacion)',
                'New Albay',
                'Tupaz',
                'Bahi',
                'Cambagang',
                'Coronobe',
                'Katipunan',
                'Lahi',
                'Langgawisan',
                'Mabugnao',
                'Magcagong',
                'Mahayahay',
                'Mauswagon',
                'New Katipunan',
                'New Manay',
                'New Panay',
                'Paloc',
                'Pamintaran',
                'Parasanon',
                'Talian',
                'Tandik',
                'Tigbao'
            ];
        } else if ($city_municipality === 'Mawab') {
            $barangays = [
                'Andili',
                'Bawani',
                'Concepcion',
                'Malinawon',
                'Nueva Visayas',
                'Nuevo Iloco',
                'Poblacion',
                'Salvacion',
                'Saosao',
                'Sawangan',
                'Tuboran'
            ];
        } else if ($city_municipality === 'Monkayo') {
            $barangays = [
                'Awao',
                'Babag',
                'Banlag',
                'Baylo',
                'Casoon',
                'Inambatan',
                'Haguimitan',
                'Macopa',
                'Mamunga',
                'Mount Diwata (Mt. Diwalwal)',
                'Naboc',
                'Olaycon',
                'Pasian (Santa Filomena)',
                'Poblacion',
                'Rizal',
                'Salvacion',
                'San Isidro',
                'San Jose',
                'Tubo-tubo (New Del Monte)',
                'Upper Ulip',
                'Union'
            ];
        } else if ($city_municipality === 'Montevista') {
            $barangays = [
                'Banagbanag',
                'Banglasan',
                'Bankerohan Norte',
                'Bankerohan Sur',
                'Camansi',
                'Camantangan',
                'Concepcion',
                'Dauman',
                'Canidkid',
                'Lebanon',
                'Linoan',
                'Mayaon',
                'New Calape',
                'New Dalaguete',
                'New Cebulan (Sambayon)',
                'New Visayas',
                'Prosperidad',
                'San Jose (Poblacion)',
                'San Vicente',
                'Tapia'
            ];
        } else if ($city_municipality === 'New Bataan') {
            $barangays = [
                'Andap',
                'Bantacan',
                'Batinao',
                'Cabinuangan (Poblacion)',
                'Camanlangan',
                'Cogonon',
                'Fatima',
                'Kahayag',
                'Katipunan',
                'Magangit',
                'Magsaysay',
                'Manurigao',
                'Pagsabangan',
                'Panag',
                'San Roque',
                'Tandawan'
            ];
        } else if ($city_municipality === 'Pantukan') {
            $barangays = [
                'Bongabong',
                'Bongbong',
                'P. Fuentes',
                'Kingking (Poblacion)',
                'Magnaga',
                'Matiao',
                'Napnapan',
                'Tagdangua',
                'Tambongon',
                'Tibagon',
                'Las Arenas',
                'Araibo',
                'Tagugpo'
            ];
        }

        # Davao del Norte
        if ($city_municipality === 'Tagum') {
            $barangays = [
                'Apokon',
                'Bincungan',
                'Busaon',
                'Canocotan',
                'Cuambogan',
                'La Filipina',
                'Liboganon',
                'Madaum',
                'Magdum',
                'Magugpo Poblacion',
                'Magugpo East',
                'Magugpo North',
                'Magugpo South',
                'Magugpo West',
                'Mankilam',
                'New Balamban',
                'Nueva Fuerza',
                'Pagsabangan',
                'Pandapan',
                'San Agustin',
                'San Isidro',
                'San Sonit (Camp 34)',
                'Visayan Village'
            ];
        } else if ($city_municipality === 'Asuncion') {
            $barangays = [
                'Binancian',
                'Buan',
                'Buclad',
                'Cabaywa',
                'Camansa',
                'Camoning',
                'Canatan',
                'Concepcion',
                'Doña Andrea',
                'Magatos',
                'Napungas',
                'New Bantayan',
                'New Santiago',
                'Pamacaun',
                'Cambanogoy (Poblacion)',
                'Sagayen',
                'San Vicente',
                'Santa Filomena',
                'Sonlon',
                'New Loon'
            ];
        } else if ($city_municipality === 'Braulio E. Dujali') {
            $barangays = [
                'Cabayangan',
                'Dujali',
                'Magupising',
                'New Casay',
                'Tanglaw'
            ];
        } else if ($city_municipality === 'Carmen') {
            $barangays = [
                'Alejal',
                'Anibongan',
                'Asuncion',
                'Cebulano',
                'Guadalupe',
                'Ising (Poblacion)',
                'La Paz',
                'Mabaus',
                'Mabuhay',
                'Magsaysay',
                'Mangalcal',
                'Minda',
                'New Camiling',
                'Salvacion',
                'San Isidro',
                'Santo Niño',
                'Taba',
                'Tibulao',
                'Tubod',
                'Tuganay'
            ];
        } else if ($city_municipality === 'Kapalong') {
            $barangays = [
                'Semong',
                'Florida',
                'Gabuyan',
                'Gupitan',
                'Capungagan',
                'Katipunan',
                'Luna',
                'Mabantao',
                'Mamacao',
                'Pag-asa',
                'Maniki (Poblacion)',
                'Sampao',
                'Sua-on',
                'Tiburcia'
            ];
        } else if ($city_municipality === 'New Corella') {
            $barangays = [
                'Cabidianan',
                'Carcor',
                'Del Monte',
                'Del Pilar',
                'El Salvador',
                'Limba-an',
                'Macgum',
                'Mambing',
                'Mesaoy',
                'New Bohol',
                'New Cortez',
                'New Sambog',
                'Patrocenio',
                'Poblacion',
                'San Roque',
                'Santa Cruz',
                'Santa Fe',
                'Santo Niño',
                'Suawon',
                'San Jose'
            ];
        } else if ($city_municipality === 'Panabo') {
            $barangays = [
                'A. O. Floirendo',
                'Datu Abdul Dadia',
                'Buenavista',
                'Cacao',
                'Cagangohan',
                'Consolacion',
                'Dapco',
                'Gredu (Poblacion)',
                'J.P. Laurel',
                'Kasilak',
                'Katipunan',
                'Katualan',
                'Kauswagan',
                'Kiotoy',
                'Little Panay',
                'Lower Panaga (Roxas)',
                'Mabunao',
                'Maduao',
                'Malativas',
                'Manay',
                'Nanyo',
                'New Malaga (Dalisay)',
                'New Malitbog',
                'New Pandan (Poblacion)',
                'New Visayas',
                'Quezon',
                'Salvacion',
                'San Francisco (Poblacion)',
                'San Nicolas',
                'San Pedro',
                'San Roque',
                'San Vicente',
                'Santa Cruz',
                'Santo Niño (Poblacion)',
                'Sindaton',
                'Southern Davao',
                'Tagpore',
                'Tibungol',
                'Upper Licanan',
                'Waterfall'
            ];
        } else if ($city_municipality === 'Samal') {
            $barangays = [
                'Adecor',
                'Anonang',
                'Aumbay',
                'Aundanao',
                'Balet',
                'Bandera',
                'Caliclic (Dangca-an)',
                'Camudmud',
                'Catagman',
                'Cawag',
                'Cogon',
                'Cogon (Talikud)',
                'Dadatan',
                'Del Monte',
                'Guilon',
                'Kanaan',
                'Kinawitnon',
                'Libertad',
                'Libuak',
                'Licup',
                'Limao',
                'Linosutan',
                'Mambago-A',
                'Mambago-B',
                'Miranda (Poblacion)',
                'Moncado (Villarica)(Poblacion)',
                'Pangubatan',
                'Peñaplata (Poblacion)',
                'Poblacion (Kaputian)',
                'San Agustin',
                'San Antonio',
                'San Isidro (Babak)',
                'San Isidro (Kaputian)',
                'San Jose (San Lapuz)',
                'San Miguel (Magamomo)',
                'San Remigio',
                'Santa Cruz (Talicod II)',
                'Santo Niño',
                'Sion (Zion)',
                'Tagbaobo',
                'Tagbay',
                'Tagbitan-ag',
                'Tagdaliao',
                'Tagpopongan',
                'Tambo',
                'Toril'
            ];
        } else if ($city_municipality === 'San Isidro') {
            $barangays = [
                'Dacudao',
                'Datu Balong',
                'Igangon',
                'Kipalili',
                'Libuton',
                'Linao',
                'Mamangan',
                'Monte Dujali',
                'Pinamuno',
                'Sabangan',
                'San Miguel',
                'Santo Niño',
                'Sawata (Poblacion)'
            ];
        } else if ($city_municipality === 'Santo Tomas') {
            $barangays = [
                'Balagunan',
                'Bobongon',
                'Casig-Ang',
                'Esperanza',
                'Kimamon',
                'Kinamayan',
                'La Libertad',
                'Lungaog',
                'Magwawa',
                'New Katipunan',
                'New Visayas',
                'Pantaron',
                'Salvacion',
                'San Jose',
                'San Miguel',
                'San Vicente',
                'Talomo',
                'Tibal-og',
                'Tulalian'
            ];
        } else if ($city_municipality === 'Talaingod') {
            $barangays = [
                'Dagohoy',
                'Palma Gil',
                'Santo Niño'
            ];
        }

        # Davao Oriental
        if ($city_municipality === 'Mati') {
            $barangays = [
                'Badas',
                'Bobon',
                'Buso',
                'Cabuaya',
                'Central (City Proper)',
                'Culian',
                'Dahican',
                'Danao',
                'Dawan',
                'Don Enrique Lopez',
                'Don Martin Marundan',
                'Don Salvador Lopez, Sr.',
                'Langka',
                'Lawigan',
                'Libudon',
                'Luban',
                'Macambol',
                'Mamali',
                'Matiao',
                'Mayo',
                'Sainz',
                'Sanghay',
                'Tagabakid',
                'Tagbinonga',
                'Taguibo',
                'Tamisan'
            ];
        } else if ($city_municipality === 'Baganga') {
            $barangays = [
                'Baculin',
                'Ban-ao',
                'Batawan',
                'Batiano',
                'Binondo',
                'Bobonao',
                'Campawan',
                'Central',
                'Dapnan',
                'Kinablangan',
                'Lambajon',
                'Lucod',
                'Mahan-ub',
                'Mikit',
                'Salingcomot',
                'San Isidro',
                'San Victor',
                'Saoquigue'
            ];
        } else if ($city_municipality === 'Banaybanay') {
            $barangays = [
                'Cabangcalan',
                'Caganganan',
                'Calubihan',
                'Causwagan',
                'Punta Linao',
                'Mahayag',
                'Maputi',
                'Mogbongcogon',
                'Panikian',
                'Pintatagan',
                'Piso Proper',
                'Poblacion',
                'San Vicente',
                'Rang-ay'
            ];
        } else if ($city_municipality === 'Boston') {
            $barangays = [
                'Cabasagan',
                'Caatihan',
                'Cawayanan',
                'Poblacion',
                'San Jose',
                'Sibajay',
                'Carmen',
                'Simulao'
            ];
        } else if ($city_municipality === 'Caraga') {
            $barangays = [
                'Alvar',
                'Caningag',
                'Don Leon Balante',
                'Lamiawan',
                'Manorigao',
                'Mercedes',
                'Palma Gil',
                'Pichon',
                'Poblacion',
                'San Antonio',
                'San Jose',
                'San Luis',
                'San Miguel',
                'San Pedro',
                'Santa Fe',
                'Santiago',
                'P.M. Sobrecarey'
            ];
        } else if ($city_municipality === 'Cateel') {
            $barangays = [
                'Abihod',
                'Alegria',
                'Aliwagwag',
                'Aragon',
                'Baybay',
                'Maglahus',
                'Mainit',
                'Malibago',
                'San Alfonso',
                'San Antonio',
                'San Miguel',
                'San Rafael',
                'San Vicente',
                'Santa Filomena',
                'Taytayan',
                'Poblacion'
            ];
        } else if ($city_municipality === 'Governor Generoso') {
            $barangays = [
                'Anitap',
                'Crispin Dela Cruz',
                'Don Aurelio Chicote',
                'Lavigan (southernmost barangay in the province)',
                'Luzon',
                'Magdug',
                'Manuel Roxas',
                'Montserrat',
                'Nangan',
                'Oregon',
                'Poblacion (Sigaboy)',
                'Pundaguitan',
                'Sergio Osmeña',
                'Surop',
                'Tagabebe',
                'Tamban',
                'Tandang Sora',
                'Tibanban',
                'Tiblawan',
                'Upper Tibanban'
            ];
        } else if ($city_municipality === 'Lupon') {
            $barangays = [
                'Bagumbayan',
                'Cabadiangan',
                'Calapagan',
                'Cocornon',
                'Corporacion',
                'Don Mariano Marcos',
                'Ilangay',
                'Langka',
                'Lantawan',
                'Limbahan',
                'Macangao',
                'Magsaysay',
                'Mahayahay',
                'Maragatas',
                'Marayag',
                'New Visayas',
                'Poblacion',
                'San Isidro',
                'San Jose',
                'Tagboa',
                'Tagugpo'
            ];
        } else if ($city_municipality === 'Manay') {
            $barangays = [
                'Capasnan',
                'Cayawan',
                'Central (Poblacion)',
                'Concepcion',
                'Del Pilar',
                'Guza',
                'Holy Cross',
                'Mabini',
                'Manreza',
                'Old Macopa',
                'Rizal',
                'San Fermin',
                'San Ignacio',
                'San Isidro',
                'Taocanga',
                'Zaragosa',
                'Lambog'
            ];
        } else if ($city_municipality === 'San Isidro') {
            $barangays = [
                'Baon',
                'Bitaogan',
                'Cambaleon',
                'Dugmanon',
                'Iba',
                'La Union',
                'Lapu-lapu',
                'Maag',
                'Manikling',
                'Maputi',
                'Batobato (Poblacion)',
                'San Miguel',
                'San Roque',
                'Santo Rosario',
                'Sudlon',
                'Talisay'
            ];
        } else if ($city_municipality === 'Tarragona') {
            $barangays = [
                'Cabagayan',
                'Central (Poblacion)',
                'Dadong',
                'Jovellar',
                'Limot',
                'Lucatan',
                'Maganda',
                'Ompao',
                'Tomoaong',
                'Tubaon'
            ];
        }

        # Davao Occidental
        if ($city_municipality === 'Malita') {
            $barangays = [
                'Bito',
                'Bolila',
                'Buhangin',
                'Culaman',
                'Datu Danwata',
                'Demoloc',
                'Felis',
                'Fishing Village',
                'Kibalatong',
                'Kidalapong',
                'Kilalag',
                'Kinangan',
                'Lacaron',
                'Lagumit',
                'Lais',
                'Little Baguio',
                'Macol',
                'Mana',
                'Manuel Peralta',
                'New Argao',
                'Pangian',
                'Pinalpalan',
                'Poblacion',
                'Sangay',
                'Talogoy',
                'Tical',
                'Ticulon',
                'Tingolo',
                'Tubalan',
                'Pangaleon'
            ];
        } else if ($city_municipality === 'Don Marcelino') {
            $barangays = [
                'Baluntaya',
                'Calian',
                'Dalupan',
                'Kinanga (Poblacion)',
                'Kiobog',
                'Lanao',
                'Lapuan',
                'Lawa',
                'Linadasan',
                'Mabuhay',
                'North Lamidan (easternmost barangay in the province)',
                'Nueva Villa',
                'South Lamidan',
                'Talaguton',
                'West Lamidan'
            ];
        } else if ($city_municipality === 'Jose Abad Santos') {
            $barangays = [
                'Balangonan',
                'Buguis',
                'Bukid',
                'Butuan',
                'Butulan',
                'Caburan Big',
                'Caburan Small (Poblacion)',
                'Camalian',
                'Carahayan',
                'Cayaponga',
                'Culaman',
                'Kalbay',
                'Kitayo',
                'Magulibas',
                'Malalan',
                'Mangile',
                'Marabatuan',
                'Meybio',
                'Molmol',
                'Nuing',
                'Patulang',
                'Quiapo',
                'San Isidro',
                'Sugal',
                'Tabayon',
                'Tanuman'
            ];
        } else if ($city_municipality === 'Santa Maria') {
            $barangays = [
                'Basiawan',
                'Buca',
                'Cadaatan',
                'Kidadan',
                'Kisulad',
                'Malalag Tubig',
                'Mamacao',
                'Ogpao',
                'Poblacion',
                'Pongpong',
                'San Agustin',
                'San Antonio',
                'San Isidro',
                'San Juan',
                'San Pedro',
                'San Roque',
                'Tanglad',
                'Santo Niño',
                'Santo Rosario',
                'Datu Daligasao',
                'Datu Intan',
                'Kinilidan'
            ];
        } else if ($city_municipality === 'Sarangani') {
            $barangays = [
                'Batuganding',
                'Konel',
                'Lipol',
                'Mabila (Poblacion)',
                'Tinina',
                'Gomtago',
                'Tagen',
                'Tucal',
                'Patuco (Sarangani Norte)',
                'Laker (Sarangani Sur)',
                'Camahual',
                'Camalig'
            ];
        }
        return $barangays;
    }
}